#print(f'Só tem espaços? {a.isspace()}')
#print(f'É numérico? {a.isnumeric()}')
#print(f'É alfabético? {a.isalpha()}')
#print(f'É alfanumérico? {a.isalnum()}')
#print(f'Está em letras maiúsculas?{a.isupper()}')
#print(f'Está em letras minúsculas? {a.islower()}')
#print(f'Está capitalizada? {a.istitle()}')

texto = input('Digite algo: ')
print(f'Possui espaços? {texto.isspace()}')
print(f'Possui números? {texto.isnumeric()}')
print(f'Possui letras? {texto.isalpha()}')
print(f'Possui letras e numeros? {texto.isalnum()}')
print(f'Possui letras maiusculas? {texto.isupper()}')
print(f'Possui letras minusculas? {texto.islower()}')
print(f'Está capitalizada? {texto.istitle()}')
